# Generated by Django 2.2.2 on 2019-06-22 18:23

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255, null=True)),
                ('calle', models.CharField(max_length=255, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('entre1', models.CharField(max_length=255, null=True)),
                ('entre2', models.CharField(max_length=255, null=True)),
                ('lineas', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('dir_norm', models.CharField(max_length=255, null=True)),
                ('metrobus', models.BooleanField()),
                ('stop_desc', models.CharField(max_length=255, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geom_98334', django.contrib.gis.db.models.fields.PointField(srid=98334)),
            ],
        ),
    ]
