# Generated by Django 2.2.2 on 2019-06-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stops',
            table='stops',
        ),
    ]
