# Generated by Django 2.2.2 on 2019-06-22 19:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_auto_20190622_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='stops',
            name='geom_98334',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=98334),
        ),
    ]
