# Generated by Django 2.2.2 on 2019-06-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0004_auto_20190622_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stops',
            new_name='Stop',
        ),
    ]
